/*globals module */
/*
    Module to define all the Configurations required
    /**

 * @type {{popularCities: string[], weatherScheduleExpression: string, topic_airport: string, secret: string, token_expiry: string, topic_boutique_category: string, topCities: string[], topic_category_swap: string, password: string, airlineScheduleExpression: string, topic_airline: string, airportScheduleExpression: string, topic_boutique: string, updateWeatherWhileAirportUpdate: boolean, topic_dvd_language: string, smpt_host: string, mqttPassword: string, smpt_secure: boolean, weatherUrl: string, airQualityPrefixUrl: string, topic_weather: string, topic_dvd_genre: string, topic_dvd_inventory: string, timeDiffToUpdateWeather: number, otp_length: number, airlineUrl: string, topic_dvd_latest: string, topic_dvd: string, airQualityPostfixUrl: string, smpt_pass: string, userName: string, topic_category: string, isApiSecured: boolean, airportUrl: string, brokerURL: string, support_email: string, smtp_port: number, topic_radio: string, smpt_user: string, mqttUsername: string, topic_dvd_subtitle: string}}
 */

let Config = function () {
    return {
        //Mongo settings
        userName: "rtc_root",
        password: "i;like;pln.,",

        //Access token settings
        isApiSecured : false,//TO-DO: update as per the requirement
        secret: "peninsula-peninsula-peninsula-peninsula",//TO-DO: update this later
        token_expiry: '300s',

        //OTP settings
        otp_length : 6,

        //Email settings
        support_email: "rtc-test@peninsula.com",//TO-DO: update this later
        smpt_host: "smtp.ethereal.email",//TO-DO: update this later
        smtp_port: 587,//TO-DO: update this later
        smpt_secure: false, // true for 465, false for other ports//TO-DO: update this later
        smpt_user: "testAccount_user",//TO-DO: update this later
        smpt_pass: "testAccount_pass",//TO-DO: update this later

        //Scheduler settings
        //exp help ::: (sec min hour day_of_month month day_of_week)
        airportScheduleExpression: '1 0 2 1 * *',//First day of every month at 2 AM
        airlineScheduleExpression: '1 0 2 1 * *',//First day of every month at 2 AM
        weatherScheduleExpression: '0 25 */1 * * *', // Every hour

        //MQTT settings
        //https://www.vultr.com/docs/how-to-install-mosquitto-mqtt-broker-server-on-ubuntu-16-04
        brokerURL: 'mqtt://ec2-54-68-100-10.us-west-2.compute.amazonaws.com',
        mqttUsername:"cms",
        mqttPassword:"cms@123",
        topic_airport: "airport",
        topic_weather: "weather",
        topic_airline: "airline",
        topic_category: "category",
        topic_category_swap: "category_swap",
        topic_boutique: "boutique",
        topic_boutique_category: "boutique_category",
        topic_dvd: "dvd",
        topic_dvd_genre: "dvd_genre",
        topic_dvd_language: "dvd_language",
        topic_dvd_subtitle: "dvd_subtitle",
        topic_dvd_inventory: "dvd_inventory",
        topic_dvd_latest: "dvd_latest",
        topic_radio: "radio",
        uuid: "UUID",

        // Public API settings
        updateWeatherWhileAirportUpdate: true,
        timeDiffToUpdateWeather : 2,
        // weatherUrl: "https://api.darksky.net/forecast/8faf203d165086b45b36443443bb8228/",
        weatherUrl: "https://api.darksky.net/forecast/a2bd82a5b0c38d78448cadf9f8858cfa/",
        airQualityPrefixUrl: "https://api.waqi.info/feed/",
        airQualityPostfixUrl: "/?token=fdac1786fa59032ede8de4a6640d8e4c919d44b4",
        airportUrl: "https://api.flightstats.com/flex/airports/rest/v1/json/all?appId=24e1354d&appKey=c26fac2248afb16a9b10995584e564b4",
        airlineUrl: "https://api.flightstats.com/flex/airlines/rest/v1/json/active?appId=24e1354d&appKey=c26fac2248afb16a9b10995584e564b4",
        popularCities: [
            "Hong Kong",
            "New Delhi",
            "Beijing",
            "Chicago",
            "Beverly hills",
            "Dubai",
            "London",
            "Manila",
            "Moscow",
            "Paris",
            "New York City",
            "Tokyo",
            "Bangkok",
            "Yangon"
        ],

        topCities: [
            "New York City",
            "Paris",
            "Rome",
            "London",
            "Jerusalem",
            "Bangkok",
            "Prague",
            "Berlin",
            "Amsterdam",
            "Madrid",
            "Munich",
            "Vienna",
            "Washington DC",
            "Brussels",
            "Tel Aviv",
            "Barcelona",
            "Istanbul",
            "Sydney",
            "Rio De Janeiro",
            "Venice",
            "Budapest",
            "Seville",
            "Granada",
            "San Francisco",
            "Cape Town",
            "Hong Kong",
            "Buenos Aires",
            "Florence",
            "Tokyo",
            "Cairo",
            "Toronto",
            "Athens",
            "Melbourne",
            "Kathmandu",
            "Montreal",
            "Edinburgh",
            "Hanoi",
            "Singapore",
            "Dublin",
            "Mexico City",
            "Krakow",
            "Las Vegas",
            "Havana",
            "Sarajevo",
            "Los Angeles",
            "Stockholm",
            "Chicago",
            "Lisbon",
            "New Orleans",
            "Ho Chi Minh City",
            "Marrakech",
            "Kyoto",
            "Moscow",
            "Shanghai",
            "Seattle",
            "Beijing",
            "Helsinki",
            "St. Petersburg",
            "Fes",
            "Phnom Penh",
            "Cusco",
            "Varanasi",
            "Luang Prabang",
            "Dubrovnik",
            "New Delhi",
            "Salvador Da Bahia",
            "Kolkata",
            "Santiago",
            "Auckland",
            "Manila",
            "Zanzibar",
            "Mumbai",
            "Hamburg",
            "Wellington",
            "Ljubljana",
            "Seoul",
            "Taipei",
            "Tallinn",
            "Lhasa",
            "Bled",
            "Siena",
            "Jaipur",
            "La Paz",
            "Quebec City",
            "Naples",
            "Heidelberg",
            "Panama City",
            "Monaco",
            "Quito",
            "Bern",
            "Cartagena",
            "Hobart",
            "Valparaiso",
            "Christchurch",
            "Dakar",
            "Bratislava",
            "Riga",
            "Copenhagen",
            "Sofia",
            "Marseille",
            "Glasgow",
            "San Juan",
            "Bath",
            "Macau",
            "Hoi An",
            "Zagreb",
            "Manchester",
            "Antigua",
            "Reykjavik",
            "Hiroshima",
            "Nairobi",
            "Vilnius",
            "Bukhara",
            "Bucharest",
            "Carcassonne",
            "Lubeck",
            "Montevideo",
            "Yangon",
            "Belgrade",
            "Dar Es Salaam ",
            "Kiev",
            "Caracas",
            "Male",
            "Tbilisi",
            "Suva",
            "Ushuaia",
            "Bogota",
            "Minsk",
            "Johannesburg",
            "Belfast",
            "Aswan",
            "Anchorage",
            "Yerevan",
            "Luxembourg",
            "Baku",
            "Addis Ababa",
            "Santo Domingo",
            "Pyongyang",
            "Almaty",
            "Mombasa",
            "Valletta",
            "Antananarivo",
            "Miami",
            "Bamako",
            "Ashgabat",
            "Oslo",
            "Milan",
            "Sao Paulo",
            "Zurich",
            "Warsaw",
            "Atlanta",
            "Guangzhou",
            "Philadelphia",
            "Lima",
            "Brisbane",
            "Casablanca",
            "Geneva",
            "Lyon",
            "San Jose",
            "Lagos",
            "Detroit",
            "Rotterdam",
            "Shenzhen",
            "Cologne",
            "Osaka",
            "Colombo",
            "Accra",
            "St. Louis",
            "Adelaide",
            "Porto",
            "Birmingham",
            "Turin",
            "Malmo",
            "Ankara",
            "Managua",
            "Salt Lake City",
            "Strasbourg",
            "Chengdu",
            "Nassau",
            "Lausanne",
            "Nuremberg",
            "Orlando",
            "Ottawa",
            "Dresden",
            "Hangzhou",
            "Pretoria",
            "Toulouse",
            "Bologna",
            "Canberra",
            "Nagoya",
            "Genoa",
            "Xian",
            "Nice",
            "Windhoek",
            "Lalibela",
            "Petra",
            "Tashkent",
            "Santorini",
            "Siem Reap",
            "Kingston",
            "Brasilia",
            "Liverpool",
            "Bergen",
            "Harare",
            "Cancun",
            "Cannes",
            "Samarkand",
            "Fukuoka",
            "Bagan",
            "Nottingham",
            "Luxor",
            "Mont St. Michel",
            "Lugano",
            "Sharm El Sheikh",
            "Punta Cana",
            "Agra",
            "Varna",
            "Honolulu",
            "Chiang Mai",
            "Haifa",
            "Thessaloniki",
            "Antalya",
            "Batumi",
            "The Hague",
            "Frankfurt",
            "Rabat",
            "Cordoba",
            "Phuket",
            "Salzburg",
            "Odessa",
            "Amman",
            "Dubai",
            "Kuala Lumpur",
            "Yalta",
            "Astana",
            "Interlaken",
            "Guatemala City",
            "Amritsar",
            "Ulaanbaatar",
            "Izmir",
            "Volgograd",
            "Recife",
            "Novosibirsk",
            "Manaus",
            "Eilat",
            "Bali",
            "Riyadh",
            "Doha",
            "Vientiane",
            "Jericho",
            "Beverly hills",
            "Delhi",
            "Pattaya",
            "Mecca",
            "Medina",
            "Chennai",
            "Johor Bahru",
            "Ha Long",
            "Jakarta",
            "Saint Petersburg",
            "Dammam",
            "Penang",
            "Iraklio",
            "Zhuhai",
            "Vancouver",
            "Marrakesh",
            "Cebu City",
            "Guilin",
            "Hurghada",
            "Mugla",
            "Chiba",
            "Frankfurt am Main",
            "Da Nang",
            "Batam",
            "Abu Dhabi",
            "Jeju",
            "Rhodes",
            "Krabi",
            "Bangalore",
            "Washington",
            "Dusseldorf",
            "Boston",
            "Tehran",
            "Houston",
            "Bogot",
            "Beirut",
            "Xiamen",
            "Dalian",
            "Pune",
            "Durban",
            "Dallas",
            "Tianjin",
            "Qingdao",

            "Denver",
            "Charlotte",
            "Kunming",
            "New York",
            "Newark",
            "Chongqing",
            "New York",
            "Phoenix",
            "Bombay",
            "Minneapolis",
            "Fort Lauderdale",
            "Jeddah",
            "Zhengzhou",
            "Nanjing",
            "Baltimore",
            "Wuhan",
            "Hyderabad",
            "Changsha",
            "Milano",
            "Urumqi",
            "Calcutta",
            "Surabaya"
        ]
    };
};

module.exports = new Config();
